import PlinkoGameClient from '../components/plinko/PlinkoGameClient';

export default function PlinkoGamePage() {
  return (
    <div className="container mx-auto p-4 max-w-7xl">
      <h1 className="text-2xl font-bold mb-6 text-white">Plinko Game</h1>
      <div className="bg-gray-900 rounded-lg shadow-xl overflow-hidden p-4">
        <PlinkoGameClient initialBalance={1000} />
      </div>
      
      {/* Provably Fair Explanation */}
      <div className="mt-8 bg-gray-800 p-6 rounded-lg shadow-lg text-gray-200">
        <h2 className="text-xl font-bold mb-4">How Provably Fair Works</h2>
        <p className="mb-4">
          Our Plinko game uses a provably fair system to ensure that game outcomes are completely fair and verifiable.
        </p>
        
        <div className="space-y-4">
          <div>
            <h3 className="font-semibold text-lg">Server Seed</h3>
            <p>A random seed generated by the server. This is kept secret until after the game, but its hash is shown before you play.</p>
          </div>
          
          <div>
            <h3 className="font-semibold text-lg">Client Seed</h3>
            <p>A seed that you can view and change. This ensures the server cannot predict or manipulate the outcome.</p>
          </div>
          
          <div>
            <h3 className="font-semibold text-lg">Nonce</h3>
            <p>A number that increases with each game played, preventing repetition of results.</p>
          </div>
          
          <div>
            <h3 className="font-semibold text-lg">Verification</h3>
            <p>After each game, you can verify that the outcome was determined by the combination of the server seed, client seed, and nonce.</p>
          </div>
        </div>
      </div>
    </div>
  );
} 